### ISSUE TITLE
Broken Python 2.7.13 support

### ISSUE THREAD

**Issue by ElCresh** [pndurette/gTTS#254] opened 2020-11-24 10:13 UTC
After updating gTTS to last version with pip it now requires urlib.parse that broke compatibility with python 2

![image](https://user-images.githubusercontent.com/9625583/100080316-f7350400-2e45-11eb-8f49-718cb1f55930.png)

**Comment by hmmbob** [comment] 2020-11-24 12:15
You do know that Python 2 was sunset almost a year ago?

https://www.python.org/doc/sunset-python-2/

**Comment by ElCresh** [comment] 2020-11-24 12:21
I know. I've transitioned all my enviroment to Python 3 but your page report Python 2.7 compatibility so I assume that is supported. Maybe a correction on that page is needed.

**Comment by hmmbob** [comment] 2020-11-24 12:25
Not my page (i'm just a passer-by), but good catch.

Maybe @pndurette can confirm  if 2.7 isn't supported anymore, or if this should be considered a bug. I'm placing my bets at the first option though ;)

**Comment by bikutaa-dev** [comment] 2020-11-24 19:57
So I've had the same problem and I need to work with 2.7.13 as that's the version that is being used for the program I'm doing scripts for is using (I have no control or involvement with said program). But I did find a solution that works for me, I went and modified the tts.py file and in the I modified line 7 to say "from urllib import quote"

**Comment by ElCresh** [comment] 2020-11-24 20:02
If I recall corrctly to restore compatibility with python 2.7.* urllib need to be replaced with urllib2 (older version of urllib userd in python 3) or an alternative like six need to be used.

But the question is: will be python 2 support dropped?

**Comment by pndurette** [comment] 2020-12-02 00:21
> I know. I've transitioned all my enviroment to Python 3 but your page report Python 2.7 compatibility so I assume that is supported. Maybe a correction on that page is needed.

Yeah, sorry about that. The issue is that it was taken away from CI (so we didn't see when it broke), but not from the package setup info.

> But the question is: will be python 2 support dropped?

For sure. There's a lot of ugly glue code everywhere, especially in tests to support the difference in Unicode string handling etc. (the usual nightmare when working with 2 and 3) that I can't wait to strip out. Just didn't take the time.

I guess #255 _could_ be reluctantly merged, and make that one of the last official 2.7 releases.

**Comment by ElCresh** [comment] 2020-12-02 00:44
Perfect. I agree with the possibility of dropping Python 2.x. I've noticed this only because I've some old Raspberry Custom Image that was shipped with Python 2.7.x by default. Last fix and then time to say goodbye.

**Comment by pndurette** [comment] 2021-02-04 04:13
Hello! gTTS `v2.2.2` is out with fixes for this!

**Closed by pndurette** 2021-02-04 04:13 UTC
