### ISSUE TITLE
Token: regexp never finds anything

### ISSUE THREAD

**Issue by tdi-odoo** [pndurette/gTTS#137] opened 2018-09-21 04:18 UTC
Hello,

I know the code yielding this error is not in this repository but the gtts-token repository seems inactive...

Since a few hours ago it seems that  one of the regular expressions when searching "TKK='integer.integer';" in Google Translate HTTP response doesn't find anything. 

Here is my Traceback:

```
gtts-cli 'hello' --output hello.mp3
Traceback (most recent call last):
  File "/usr/local/bin/gtts-cli", line 9, in <module>
    load_entry_point('gTTS==2.0.1', 'console_scripts', 'gtts-cli')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gtts/cli.py", line 194, in tts_cli
    tts.write_to_fp(output)
  File "/usr/local/lib/python2.7/dist-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py", line 62, in _get_token_key
    a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

Is it possible this is caused by a modification in Google Translate HTTP response? I tried with other google translate python apps and they also fail to find the token...

Best regards,
Thomas

**Comment by pndurette** [comment] 2018-09-21 06:16
It’s very possible they’ve changed the way they do things.. :|

Will have to check. The token is calculated in JavaScript. So it’s all about seeing what changed (if that’s the issue). 

Been very busy lately, which is why I haven’t spent a significant amount of time giving lots of TLC do gTTS. 

--
Pierre Nick Durette

**Comment by chathurangawijetunge** [comment] 2018-09-21 06:42
Yes it's not working

**Comment by ElCresh** [comment] 2018-09-21 08:04
Yes. Same issue for me on RPi3.

**Comment by letitbe1503** [comment] 2018-09-21 09:57
I'm not expert in reg expression so i change like this and work now

/usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py
comment 3 line  and add 6 line
#        tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
#        a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
#        b = re.search("b\\\\x3d(-?\d+);", tkk_expr).group(1)
        lineStr = line
        lineStr = lineStr[lineStr.index("TKK")+5:len(lineStr)]
        lineStr = lineStr[0:lineStr.index("'")]
        lineArr =  lineStr.split(".")
        a =  lineArr[0]
        b =  lineArr[1]


etc. 
I have another Google Text-to-Speech app develop by delphi 
I this not change anything now my app still work

**Comment by gubgbugbugvjgvugv** [comment] 2018-09-21 11:18
Now it's producing another error ;((
`Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts_token\gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts_token\gtts_token.py", line 58, in _get_token_key
    response = requests.get("https://translate.google.com/")
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Desktop\programming\Python_code\new.py", line 3, in <module>
    tts.save('hello.mp3')
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 247, in save
    self.write_to_fp(f)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 192, in write_to_fp
    str(e))
gtts.tts.gTTSError: Connection error during token calculation: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`

**Comment by gubgbugbugvjgvugv** [comment] 2018-09-21 11:34
Now I am getting this error :((

> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
>     (self.host, self.port), self.timeout, **extra_kw)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\socket.py", line 743, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 11001] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 284, in connect
>     conn = self._new_conn()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 440, in send
>     timeout=timeout
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 187, in write_to_fp
>     part_tk = self.token.calculate_token(part)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts_token\gtts_token.py", line 28, in calculate_token
>     seed = self._get_token_key()
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts_token\gtts_token.py", line 58, in _get_token_key
>     response = requests.get("https://translate.google.com/")
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 72, in get
>     return request('get', url, params=params, **kwargs)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 58, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 508, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\HP\Desktop\Desktop\programming\Python_code\new.py", line 3, in <module>
>     tts.save('hello.mp3')
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 247, in save
>     self.write_to_fp(f)
>   File "C:\Users\HP\AppData\Local\Programs\Python\Python36\lib\site-packages\gtts\tts.py", line 192, in write_to_fp
>     str(e))
> gtts.tts.gTTSError: Connection error during token calculation: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D7C8B53710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by gubgbugbugvjgvugv** [comment] 2018-09-21 11:36
> I'm not expert in reg expression so i change like this and working now
> 
> /usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py
> comment 3 line and add 6 line
> 
> ```python
> #        tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
> #        a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
> #        b = re.search("b\\\\x3d(-?\d+);", tkk_expr).group(1)
>         lineStr = line
>         lineStr = lineStr[lineStr.index("TKK='")+5:len(lineStr)]
>         lineStr = lineStr[0:lineStr.index("'")]
>         lineArr =  lineStr.split(".")
>         a =  lineArr[0]
>         b =  lineArr[1]
> ```
> 
> etc.
> I have another Google Text-to-Speech app develop by delphi
> I this not change anything now my app still work

Thank You It solved my problem 
Can you explain the problem?

**Comment by rupdev** [comment] 2018-09-21 11:54
Thank you so much for trying to fix this issue. As a newbie I really don't know how to apply letitbe1503 solution. gTTS is the best.

**Comment by rupdev** [comment] 2018-09-21 12:00
> I'm not expert in reg expression so i change like this and working now
> 
> /usr/local/lib/python2.7/dist-packages/gtts_token/gtts_token.py
> comment 3 line and add 6 line
> 
> ```python
> #        tkk_expr = re.search(".*?(TKK=.*?;)W.*?", line).group(1)
> #        a = re.search("a\\\\x3d(-?\d+);", tkk_expr).group(1)
> #        b = re.search("b\\\\x3d(-?\d+);", tkk_expr).group(1)
>         lineStr = line
>         lineStr = lineStr[lineStr.index("TKK='")+5:len(lineStr)]
>         lineStr = lineStr[0:lineStr.index("'")]
>         lineArr =  lineStr.split(".")
>         a =  lineArr[0]
>         b =  lineArr[1]
> ```
> 
> etc.
> I have another Google Text-to-Speech app develop by delphi
> I this not change anything now my app still work

Thank you for that!

**Comment by chathurangawijetunge** [comment] 2018-09-21 12:35
When will this be fixed in gTTS

**Comment by ilevn** [comment] 2018-09-21 12:44
That's hard to say as this exception is the result of a faulty regex handler in another repo (for which I've submitted a pull request) that is rather inactive as of now.

However, in the meantime you can monkey-patch the affected function like so:

```py
import re
import requests
from gtts import gTTS
from gtts_token.gtts_token import Token

def _patch_faulty_function(self):
    if self.token_key is not None:
        return self.token_key

    timestamp = calendar.timegm(time.gmtime())
    hours = int(math.floor(timestamp / 3600))

    import requests
    response = requests.get("https://translate.google.com/")
    line = response.text.split('\n')[-1]

    parsed = re.search("(?:TKK='(?:(\d+)\.(\d+))';)", line)
    a, b = parsed.groups()

    result = str(hours) + "." + str(int(a) + int(b))
    self.token_key = result
    return result


# Monkey patch faulty function.
Token._get_token_key = _patch_faulty_function

# Then call it normally.
tts = gTTS('hello')
tts.save('hello.mp3')
```
I hope that helps.

**Comment by Guy-Dipietro-Bose** [comment] 2018-09-21 15:14
I've likewise put up a PR to address the issue in gtts_token: https://github.com/Boudewijn26/gTTS-token/pull/8

**Comment by ggqq12356** [comment] 2018-09-21 16:13
i have same problem today <br>

**[My solution]**<br><br>
I checked the code of line 64, in gtts_token.py

and i try to print(a), but it show a None type

so i repair that bug in line 64:

`# bug`<br>
`# a = re.search(“a\\\\x3d(-?\d+);”, tkk_expr).group(1)`<br>
`# b = re.search(“b\\\\x3d(-?\d+);”, tkk_expr).group(1)`<br>

`# debug`<br>
`tkk = tkk_expr.replace(“\’”, “”).split(“;”)[0].split(“=”)[1]`<br>
`a = tkk.split(“.”)[0]`<br>
`b = tkk.split(“.”)[1]`<br>
— — — — — — — — — — — — — — — — — — — — — — — — — — — —
and it’s work~

**Comment by Guy-Dipietro-Bose** [comment] 2018-09-21 17:16
Fix was merged into gtts-token. This should be fixed now.

**Comment by Boudewijn26** [comment] 2018-09-21 17:28
[gTTS-token 1.1.2 has just been released](https://pypi.org/manage/project/gTTS-token/release/1.1.2/). Thanks a lot for the work everyone. It's good to see something I've created years ago still being cared about.

**Comment by ilevn** [comment] 2018-09-21 17:29
And thank you for putting in all the work to create something like this

**Comment by pndurette** [comment] 2018-09-21 20:50
@Boudewijn26 You and @guydipietro both rock! Amazing!

**Comment by pndurette** [comment] 2018-09-21 20:59
Re-ran Travis build on `master`, [all good](https://travis-ci.org/pndurette/gTTS/builds/394396311)!

**Closed** 2018-09-21 20:59 UTC

**Comment by Creator-360** [comment] 2018-09-23 10:30
hello, I try today to use the gtts on python but is not working
can somebody help me please ?

the error is:

Exception has occurred: OSError
[Errno 22] Invalid argument: 'C:\test.mp3'
  File "C:\Users\Administrator\Desktop\Speech-Recognition.py", line 39, in <module>
    speech.save("C:\test.mp3")

My code:

import speech_recognition as sr
from gtts import gTTS
import os
import playsound

while True:

    command = 0
    speech = 0

    mic = sr.Microphone()
    r = sr.Recognizer()
    with mic as source:
        print("Calibrate Microphone")
        print("Please wait...")
        r.adjust_for_ambient_noise(source, duration=1)
        print("listening...")
        audio = r.listen(source)

    try:
        command = (r.recognize_google(audio))
        print("you said:"+command)

    except sr.UnknownValueError:
        print("")


    except sr.RequestError:
        print("")

    if "hello" in command:
        print("hello")
        speech = gTTS("hello", lang="en")
        if os.path.exists("C:\test.mp3"):
            print("file exist")
            playsound.playsound("C:\test.mp3", True)
        else:
            print("saving new mp3 sound")
            speech.save("C:\test.mp3")
            playsound.playsound("C:\test.mp3", True)

**Comment by Boudewijn26** [comment] 2018-09-23 15:41
Hi Creator-360,

The error indicated that the argument `'C:\test.mp3'` is invalid. Perhaps gTTS expects forward slashes: `'C:/test.mp3'`. This appears to be unrelated to the issues other people were having, those triggered `AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by Hoeby** [comment] 2018-10-11 19:33
i have a problem, where i am forwarded to this issue.

When going to the directory: /usr/local/lib/python2.7/dist-packages/
I can't find a gtts_token directory. Does somebody now where to find the .py gTTS file?

**Comment by Akavall** [comment] 2018-11-29 05:19
It is not working for me. The main problem seems to be the response that I get after:

```
response = requests.get("https://translate.google.com/")
```
This certainly looks wrong, 
```
In [6]: line = response.text.split('\n')[-1]

In [7]: line
Out[7]: '</script>      </body> </html>'
```
This was working fine yesterday.

**Comment by n8wachT** [comment] 2018-11-29 07:31
> This was working fine yesterday.

Stopped working for me too over night, glad I'm not the only one

**Comment by rupdev** [comment] 2018-11-29 10:21
> > This was working fine yesterday.
> 
> Stopped working for me too over night, glad I'm not the only one

Yes, gTTS has stopped working. the 'NoneType' object has no attribute 'groups'

**Comment by intermediatech** [comment] 2018-11-29 13:05
Try this.. It works now.

```
import calendar
import time
import math
import re
import requests
from gtts import gTTS
from gtts_token.gtts_token import Token

def _patch_faulty_function(self):
    if self.token_key is not None:
        return self.token_key

    timestamp = calendar.timegm(time.gmtime())
    hours = int(math.floor(timestamp / 3600))

    results = requests.get("https://translate.google.com/")
    tkk_expr = re.search("(tkk:*?'\d{2,}.\d{3,}')", results.text).group(1)
    tkk = re.search("(\d{5,}.\d{6,})", tkk_expr).group(1)
    
    a , b = tkk.split('.')

    result = str(hours) + "." + str(int(a) + int(b))
    self.token_key = result
    return result


# Monkey patch faulty function.
Token._get_token_key = _patch_faulty_function

# Then call it normally.
tts = gTTS("Hello World")
tts.save('hello.mp3')
```

Worked on code by @ilevn 
Thanks @ilevn

**Comment by kaushaljjw206** [comment] 2018-11-29 16:10
> Try this.. It works now.
> 
> ```python
> import calendar
> import time
> import math
> import re
> import requests
> from gtts import gTTS
> from gtts_token.gtts_token import Token
> 
> def _patch_faulty_function(self):
>     if self.token_key is not None:
>         return self.token_key
> 
>     timestamp = calendar.timegm(time.gmtime())
>     hours = int(math.floor(timestamp / 3600))
> 
>     results = requests.get("https://translate.google.com/")
>     tkk_expr = re.search("(tkk:*?'\d{2,}.\d{3,}')", results.text).group(1)
>     tkk = re.search("(\d{5,}.\d{6,})", tkk_expr).group(1)
>     
>     a , b = tkk.split('.')
> 
>     result = str(hours) + "." + str(int(a) + int(b))
>     self.token_key = result
>     return result
> 
> 
> # Monkey patch faulty function.
> Token._get_token_key = _patch_faulty_function
> 
> # Then call it normally.
> tts = gTTS("Hello World")
> tts.save('hello.mp3')
> ```
> 
> Worked on code by @ilevn
> Thanks @ilevn

Thank You for the solution
Its working now

**Comment by Boudewijn26** [comment] 2018-11-30 08:38
gTTS-token 1.1.3 indeed contains the fixes for the latest Google Translate update. Please update and verify it's working as expected

**Comment by bretan12** [comment] 2018-12-06 06:20
When i run the below code 

from gtts import gTTS
import os

tts = gTTS('Hello World',lang='en')
tts.save('good.mp3')
os.system('good.mp3')

I get this error

Traceback (most recent call last):
tts = gTTS('Hello World',lang='en')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\gtts\tts.py", line 105, in __init__
    for k, v in locals().items():
RuntimeError: dictionary changed size during iteration

I don't have any idea of how I should solve this problem.
Please help.

**Comment by mihirbhavsar** [comment] 2018-12-07 08:19
Traceback (most recent call last):
  File "/home/pi/GassistPi/src/main.py", line 692, in <module>
    Myassistant().main()
  File "/home/pi/GassistPi/src/main.py", line 554, in main
    radio(str(usrcmd).lower())
  File "/home/pi/GassistPi/src/actions.py", line 282, in radio
    say("Tuning into " + conv)
  File "/home/pi/GassistPi/src/actions.py", line 229, in say
    tts.save(ttsfilename)
  File "/home/pi/env/lib/python3.5/site-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/home/pi/env/lib/python3.5/site-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/home/pi/env/lib/python3.5/site-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/home/pi/env/lib/python3.5/site-packages/gtts_token/gtts_token.py", line 59, in _get_token_key
    lineStr = lineStr[lineStr.index("TKK='")+5:len(lineStr)]
ValueError: substring not found

any solution for this error?

**Comment by Tobils** [comment] 2019-01-03 02:35
> Try this.. It works now.
> 
> ```python
> import calendar
> import time
> import math
> import re
> import requests
> from gtts import gTTS
> from gtts_token.gtts_token import Token
> 
> def _patch_faulty_function(self):
>     if self.token_key is not None:
>         return self.token_key
> 
>     timestamp = calendar.timegm(time.gmtime())
>     hours = int(math.floor(timestamp / 3600))
> 
>     results = requests.get("https://translate.google.com/")
>     tkk_expr = re.search("(tkk:*?'\d{2,}.\d{3,}')", results.text).group(1)
>     tkk = re.search("(\d{5,}.\d{6,})", tkk_expr).group(1)
>     
>     a , b = tkk.split('.')
> 
>     result = str(hours) + "." + str(int(a) + int(b))
>     self.token_key = result
>     return result
> 
> 
> # Monkey patch faulty function.
> Token._get_token_key = _patch_faulty_function
> 
> # Then call it normally.
> tts = gTTS("Hello World")
> tts.save('hello.mp3')
> ```
> 
> Worked on code by @ilevn
> Thanks @ilevn

I have same issue and fortunately its work for me, thanks for sharing. thanks @ilevn

**Comment by DiegoBneiNoah** [comment] 2019-11-24 03:29
> When will this be fixed in gTTS
> Eg:- in
> pip3 install gTTS

I trying `gtts-cli -l pt -f file.txt -o output.mp3` and got message from `import gtts from tts_cli not found`. I had lost the module and making pip3 gTTS I could get it working again. ThankX!
